# DO NOT EDIT THIS FILE
from dataclasses import dataclass, field
from typing import Optional

@dataclass
class ListNode:
    val: int=field(default=0)
    next: Optional["ListNode"]=field(default=None)

    def __str__(self) -> str:
        return f'ListNode({self.val}, {self.next})'
    
@dataclass
class TreeNode:
    val: int=field(default=0)
    left: Optional["TreeNode"]=field(default=None)
    right: Optional["TreeNode"]=field(default=None)

    def __str__(self) -> str:
        return f'TreeNode({self.val}, {self.left}, {self.right})'

